version: '3.8'

services:
  web:
    build:
      context: ..
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db_weather
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
